/* 
 * api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LoginApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LoginApiTests
    {
        private LoginApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LoginApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LoginApi
            //Assert.IsInstanceOfType(typeof(LoginApi), instance, "instance is a LoginApi");
        }

        
        /// <summary>
        /// Test Off
        /// </summary>
        [Test]
        public void OffTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Off();
            //Assert.IsInstanceOf<ApiResult> (response, "response is ApiResult");
        }
        
        /// <summary>
        /// Test On
        /// </summary>
        [Test]
        public void OnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.On();
            //Assert.IsInstanceOf<ApiResultLoginUser> (response, "response is ApiResultLoginUser");
        }
        
        /// <summary>
        /// Test PwdOn
        /// </summary>
        [Test]
        public void PwdOnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserLogin login = null;
            //var response = instance.PwdOn(login);
            //Assert.IsInstanceOf<ApiResultLoginUser> (response, "response is ApiResultLoginUser");
        }
        
        /// <summary>
        /// Test UpdateAvatar
        /// </summary>
        [Test]
        public void UpdateAvatarTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream _file = null;
            //var response = instance.UpdateAvatar(_file);
            //Assert.IsInstanceOf<ApiResultString> (response, "response is ApiResultString");
        }
        
        /// <summary>
        /// Test UpdateNickName
        /// </summary>
        [Test]
        public void UpdateNickNameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nickName = null;
            //var response = instance.UpdateNickName(nickName);
            //Assert.IsInstanceOf<ApiResult> (response, "response is ApiResult");
        }
        
        /// <summary>
        /// Test UpdatePwd
        /// </summary>
        [Test]
        public void UpdatePwdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewPwd newpwd = null;
            //var response = instance.UpdatePwd(newpwd);
            //Assert.IsInstanceOf<ApiResult> (response, "response is ApiResult");
        }
        
        /// <summary>
        /// Test WeChatAppId
        /// </summary>
        [Test]
        public void WeChatAppIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WeChatAppId();
            //Assert.IsInstanceOf<ApiResultString> (response, "response is ApiResultString");
        }
        
        /// <summary>
        /// Test WeChatOn
        /// </summary>
        [Test]
        public void WeChatOnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //bool? testLogin = null;
            //var response = instance.WeChatOn(code, testLogin);
            //Assert.IsInstanceOf<ApiResultLoginUser> (response, "response is ApiResultLoginUser");
        }
        
    }

}
