/**
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PagedResultUser } from './pagedResultUser';


export interface ApiResultPagedResultUser { 
    readonly data?: PagedResultUser;
    readonly error?: string;
    readonly result?: boolean;
}
