/**
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Configs { 
    appConfigs?: Configs.AppConfigsEnum;
    serviceMessages?: Configs.ServiceMessagesEnum;
    permissionDescriptions?: Configs.PermissionDescriptionsEnum;
    uiLangs?: Configs.UiLangsEnum;
}
export namespace Configs {
    export type AppConfigsEnum = 'CONFIG_MAX_FILE_SIZE' | 'CONFIG_MENUS' | 'CONFIG_EDITOR_STYLES' | 'CONFIG_EDITOR_STYLE_TAG' | 'CONFIG_DAILY_TAG' | 'CONFIG_SANDBOX_APP_TAG' | 'CONFIG_LOGO' | 'CONFIG_BG' | 'CONFIG_DEFAULT_AVATAR' | 'CONFIG_TITLE' | 'CONFIG_DOC_TYPE_TAG' | 'CONFIG_SOLUTION_TYPE_TAG' | 'CONFIG_APP_TAG' | 'CONFIG_SCRIPT_TAG' | 'CONFIG_AUTOPLAY_TAG' | 'CONFIG_PWD_EXP' | 'CONFIG_WX_API_URL' | 'CONFIG_WX_API_TOKEN' | 'CONFIG_WX_JS_DOMAIN' | 'CONFIG_WX_APP_ID' | 'CONFIG_WX_APP_SECRET' | 'CONFIG_WX_API_URL_TOKEN' | 'CONFIG_WX_ENABLED' | 'CONFIG_ICP' | 'CONFIG_WX_API_URL_MENU' | 'CONFIG_WX_API_URL_SENDALL' | 'CONFIG_WX_API_URL_PREVIEW' | 'CONFIG_WX_API_URL_UPLOAD' | 'CONFIG_WX_API_URL_UPLOAD_IMG' | 'CONFIG_WX_API_PREVIEW_USERID' | 'CONFIG_WX_API_URL_UPLOAD_NEWS' | 'CONFIG_WX_API_URL_DELETE_MSG' | 'CONFIG_HOME_URL' | 'CONFIG_WX_SHARE_TAG' | 'CONFIG_WX_SHARE_DEFAULT_THUMB' | 'CONFIG_WX_SHARE_DEFAULT_THUMB_ID' | 'CONFIG_WX_SHARE_MAX_ARTICLE_COUNT';
    export const AppConfigsEnum = {
        MAXFILESIZE: 'CONFIG_MAX_FILE_SIZE' as AppConfigsEnum,
        MENUS: 'CONFIG_MENUS' as AppConfigsEnum,
        EDITORSTYLES: 'CONFIG_EDITOR_STYLES' as AppConfigsEnum,
        EDITORSTYLETAG: 'CONFIG_EDITOR_STYLE_TAG' as AppConfigsEnum,
        DAILYTAG: 'CONFIG_DAILY_TAG' as AppConfigsEnum,
        SANDBOXAPPTAG: 'CONFIG_SANDBOX_APP_TAG' as AppConfigsEnum,
        LOGO: 'CONFIG_LOGO' as AppConfigsEnum,
        BG: 'CONFIG_BG' as AppConfigsEnum,
        DEFAULTAVATAR: 'CONFIG_DEFAULT_AVATAR' as AppConfigsEnum,
        TITLE: 'CONFIG_TITLE' as AppConfigsEnum,
        DOCTYPETAG: 'CONFIG_DOC_TYPE_TAG' as AppConfigsEnum,
        SOLUTIONTYPETAG: 'CONFIG_SOLUTION_TYPE_TAG' as AppConfigsEnum,
        APPTAG: 'CONFIG_APP_TAG' as AppConfigsEnum,
        SCRIPTTAG: 'CONFIG_SCRIPT_TAG' as AppConfigsEnum,
        AUTOPLAYTAG: 'CONFIG_AUTOPLAY_TAG' as AppConfigsEnum,
        PWDEXP: 'CONFIG_PWD_EXP' as AppConfigsEnum,
        WXAPIURL: 'CONFIG_WX_API_URL' as AppConfigsEnum,
        WXAPITOKEN: 'CONFIG_WX_API_TOKEN' as AppConfigsEnum,
        WXJSDOMAIN: 'CONFIG_WX_JS_DOMAIN' as AppConfigsEnum,
        WXAPPID: 'CONFIG_WX_APP_ID' as AppConfigsEnum,
        WXAPPSECRET: 'CONFIG_WX_APP_SECRET' as AppConfigsEnum,
        WXAPIURLTOKEN: 'CONFIG_WX_API_URL_TOKEN' as AppConfigsEnum,
        WXENABLED: 'CONFIG_WX_ENABLED' as AppConfigsEnum,
        ICP: 'CONFIG_ICP' as AppConfigsEnum,
        WXAPIURLMENU: 'CONFIG_WX_API_URL_MENU' as AppConfigsEnum,
        WXAPIURLSENDALL: 'CONFIG_WX_API_URL_SENDALL' as AppConfigsEnum,
        WXAPIURLPREVIEW: 'CONFIG_WX_API_URL_PREVIEW' as AppConfigsEnum,
        WXAPIURLUPLOAD: 'CONFIG_WX_API_URL_UPLOAD' as AppConfigsEnum,
        WXAPIURLUPLOADIMG: 'CONFIG_WX_API_URL_UPLOAD_IMG' as AppConfigsEnum,
        WXAPIPREVIEWUSERID: 'CONFIG_WX_API_PREVIEW_USERID' as AppConfigsEnum,
        WXAPIURLUPLOADNEWS: 'CONFIG_WX_API_URL_UPLOAD_NEWS' as AppConfigsEnum,
        WXAPIURLDELETEMSG: 'CONFIG_WX_API_URL_DELETE_MSG' as AppConfigsEnum,
        HOMEURL: 'CONFIG_HOME_URL' as AppConfigsEnum,
        WXSHARETAG: 'CONFIG_WX_SHARE_TAG' as AppConfigsEnum,
        WXSHAREDEFAULTTHUMB: 'CONFIG_WX_SHARE_DEFAULT_THUMB' as AppConfigsEnum,
        WXSHAREDEFAULTTHUMBID: 'CONFIG_WX_SHARE_DEFAULT_THUMB_ID' as AppConfigsEnum,
        WXSHAREMAXARTICLECOUNT: 'CONFIG_WX_SHARE_MAX_ARTICLE_COUNT' as AppConfigsEnum
    };
    export type ServiceMessagesEnum = 'SiteConfigError' | 'FileToLarge' | 'ClientError' | 'ConflictRoleName' | 'ConflictNodeName' | 'ConflictUserName' | 'InvalidPwd' | 'InvalidRoleName' | 'InvalidUserName' | 'InvalidNodeName' | 'InvalidUserState' | 'NeedRelogin' | 'NoPermission' | 'NoSuchBaseRole' | 'NoSuchPermission' | 'NoSuchRole' | 'NoSuchUser' | 'NotLogin' | 'ServerError' | 'UserOrPwdError' | 'NoSuchFolder' | 'NoSuchFile' | 'NoSuchNode' | 'InvalidFileType' | 'ConflictTagName' | 'NoSuchTag' | 'InvalidTagName' | 'InvalidTagValues' | 'NoSuchLang' | 'InvalidQuery' | 'NoSuchComment';
    export const ServiceMessagesEnum = {
        SiteConfigError: 'SiteConfigError' as ServiceMessagesEnum,
        FileToLarge: 'FileToLarge' as ServiceMessagesEnum,
        ClientError: 'ClientError' as ServiceMessagesEnum,
        ConflictRoleName: 'ConflictRoleName' as ServiceMessagesEnum,
        ConflictNodeName: 'ConflictNodeName' as ServiceMessagesEnum,
        ConflictUserName: 'ConflictUserName' as ServiceMessagesEnum,
        InvalidPwd: 'InvalidPwd' as ServiceMessagesEnum,
        InvalidRoleName: 'InvalidRoleName' as ServiceMessagesEnum,
        InvalidUserName: 'InvalidUserName' as ServiceMessagesEnum,
        InvalidNodeName: 'InvalidNodeName' as ServiceMessagesEnum,
        InvalidUserState: 'InvalidUserState' as ServiceMessagesEnum,
        NeedRelogin: 'NeedRelogin' as ServiceMessagesEnum,
        NoPermission: 'NoPermission' as ServiceMessagesEnum,
        NoSuchBaseRole: 'NoSuchBaseRole' as ServiceMessagesEnum,
        NoSuchPermission: 'NoSuchPermission' as ServiceMessagesEnum,
        NoSuchRole: 'NoSuchRole' as ServiceMessagesEnum,
        NoSuchUser: 'NoSuchUser' as ServiceMessagesEnum,
        NotLogin: 'NotLogin' as ServiceMessagesEnum,
        ServerError: 'ServerError' as ServiceMessagesEnum,
        UserOrPwdError: 'UserOrPwdError' as ServiceMessagesEnum,
        NoSuchFolder: 'NoSuchFolder' as ServiceMessagesEnum,
        NoSuchFile: 'NoSuchFile' as ServiceMessagesEnum,
        NoSuchNode: 'NoSuchNode' as ServiceMessagesEnum,
        InvalidFileType: 'InvalidFileType' as ServiceMessagesEnum,
        ConflictTagName: 'ConflictTagName' as ServiceMessagesEnum,
        NoSuchTag: 'NoSuchTag' as ServiceMessagesEnum,
        InvalidTagName: 'InvalidTagName' as ServiceMessagesEnum,
        InvalidTagValues: 'InvalidTagValues' as ServiceMessagesEnum,
        NoSuchLang: 'NoSuchLang' as ServiceMessagesEnum,
        InvalidQuery: 'InvalidQuery' as ServiceMessagesEnum,
        NoSuchComment: 'NoSuchComment' as ServiceMessagesEnum
    };
    export type PermissionDescriptionsEnum = 'PERMISSION_MANAGE' | 'PERMISSION_POST_BLOG' | 'PERMISSION_REPLY_SOLUTION' | 'PERMISSION_SHARE_BLOG' | 'PERMISSION_COMMENT' | 'PERMISSION_THIRD_SHARE';
    export const PermissionDescriptionsEnum = {
        MANAGE: 'PERMISSION_MANAGE' as PermissionDescriptionsEnum,
        POSTBLOG: 'PERMISSION_POST_BLOG' as PermissionDescriptionsEnum,
        REPLYSOLUTION: 'PERMISSION_REPLY_SOLUTION' as PermissionDescriptionsEnum,
        SHAREBLOG: 'PERMISSION_SHARE_BLOG' as PermissionDescriptionsEnum,
        COMMENT: 'PERMISSION_COMMENT' as PermissionDescriptionsEnum,
        THIRDSHARE: 'PERMISSION_THIRD_SHARE' as PermissionDescriptionsEnum
    };
    export type UiLangsEnum = 'Library' | 'Name' | 'UserName' | 'Password' | 'Manage' | 'User' | 'Role' | 'State' | 'Normal' | 'Disabled' | 'Search' | 'Create' | 'Permission' | 'Delete' | 'RootNode' | 'AddSolution' | 'Solution' | 'Folder' | 'Blog' | 'NoSolution' | 'Select' | 'Ok' | 'Preview' | 'Cancle' | 'ConfirmNameToDelete' | 'Tags' | 'Type' | 'Value' | 'Values' | 'None' | 'Bool' | 'String' | 'Enum' | 'Number' | 'Url' | 'Private' | 'Modify' | 'Key' | 'DefaultValue' | 'Reset' | 'Configs' | 'Login' | 'Logout' | 'History' | 'Mine' | 'MySolution' | 'SolutionTo' | 'ReplySolution' | 'ViewSolution' | 'MySolutions' | 'ImageEditor' | 'LoadMore' | 'Comment' | 'ChangePwd' | 'NewPassword' | 'PasswordNotSame' | 'LivePreview' | 'BlogEditor' | 'DataWillNotSave' | 'Python' | 'CommentSuccess' | 'NoCommentsWelcomeToAdd' | 'Run' | 'TmpFileWillNotSave' | 'NoWxTokenFound' | 'InvalidApiSignature' | 'Reference' | 'PwdDescription';
    export const UiLangsEnum = {
        Library: 'Library' as UiLangsEnum,
        Name: 'Name' as UiLangsEnum,
        UserName: 'UserName' as UiLangsEnum,
        Password: 'Password' as UiLangsEnum,
        Manage: 'Manage' as UiLangsEnum,
        User: 'User' as UiLangsEnum,
        Role: 'Role' as UiLangsEnum,
        State: 'State' as UiLangsEnum,
        Normal: 'Normal' as UiLangsEnum,
        Disabled: 'Disabled' as UiLangsEnum,
        Search: 'Search' as UiLangsEnum,
        Create: 'Create' as UiLangsEnum,
        Permission: 'Permission' as UiLangsEnum,
        Delete: 'Delete' as UiLangsEnum,
        RootNode: 'RootNode' as UiLangsEnum,
        AddSolution: 'AddSolution' as UiLangsEnum,
        Solution: 'Solution' as UiLangsEnum,
        Folder: 'Folder' as UiLangsEnum,
        Blog: 'Blog' as UiLangsEnum,
        NoSolution: 'NoSolution' as UiLangsEnum,
        Select: 'Select' as UiLangsEnum,
        Ok: 'Ok' as UiLangsEnum,
        Preview: 'Preview' as UiLangsEnum,
        Cancle: 'Cancle' as UiLangsEnum,
        ConfirmNameToDelete: 'ConfirmNameToDelete' as UiLangsEnum,
        Tags: 'Tags' as UiLangsEnum,
        Type: 'Type' as UiLangsEnum,
        Value: 'Value' as UiLangsEnum,
        Values: 'Values' as UiLangsEnum,
        None: 'None' as UiLangsEnum,
        Bool: 'Bool' as UiLangsEnum,
        String: 'String' as UiLangsEnum,
        Enum: 'Enum' as UiLangsEnum,
        Number: 'Number' as UiLangsEnum,
        Url: 'Url' as UiLangsEnum,
        Private: 'Private' as UiLangsEnum,
        Modify: 'Modify' as UiLangsEnum,
        Key: 'Key' as UiLangsEnum,
        DefaultValue: 'DefaultValue' as UiLangsEnum,
        Reset: 'Reset' as UiLangsEnum,
        Configs: 'Configs' as UiLangsEnum,
        Login: 'Login' as UiLangsEnum,
        Logout: 'Logout' as UiLangsEnum,
        History: 'History' as UiLangsEnum,
        Mine: 'Mine' as UiLangsEnum,
        MySolution: 'MySolution' as UiLangsEnum,
        SolutionTo: 'SolutionTo' as UiLangsEnum,
        ReplySolution: 'ReplySolution' as UiLangsEnum,
        ViewSolution: 'ViewSolution' as UiLangsEnum,
        MySolutions: 'MySolutions' as UiLangsEnum,
        ImageEditor: 'ImageEditor' as UiLangsEnum,
        LoadMore: 'LoadMore' as UiLangsEnum,
        Comment: 'Comment' as UiLangsEnum,
        ChangePwd: 'ChangePwd' as UiLangsEnum,
        NewPassword: 'NewPassword' as UiLangsEnum,
        PasswordNotSame: 'PasswordNotSame' as UiLangsEnum,
        LivePreview: 'LivePreview' as UiLangsEnum,
        BlogEditor: 'BlogEditor' as UiLangsEnum,
        DataWillNotSave: 'DataWillNotSave' as UiLangsEnum,
        Python: 'Python' as UiLangsEnum,
        CommentSuccess: 'CommentSuccess' as UiLangsEnum,
        NoCommentsWelcomeToAdd: 'NoCommentsWelcomeToAdd' as UiLangsEnum,
        Run: 'Run' as UiLangsEnum,
        TmpFileWillNotSave: 'TmpFileWillNotSave' as UiLangsEnum,
        NoWxTokenFound: 'NoWxTokenFound' as UiLangsEnum,
        InvalidApiSignature: 'InvalidApiSignature' as UiLangsEnum,
        Reference: 'Reference' as UiLangsEnum,
        PwdDescription: 'PwdDescription' as UiLangsEnum
    };
}
