/**
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NodeTag } from './nodeTag';


export interface NodeReference { 
    id?: string;
    type?: NodeReference.TypeEnum;
    content?: string;
    tags?: Array<NodeTag>;
}
export namespace NodeReference {
    export type TypeEnum = 'None' | 'Folder' | 'Blog' | 'Reference';
    export const TypeEnum = {
        None: 'None' as TypeEnum,
        Folder: 'Folder' as TypeEnum,
        Blog: 'Blog' as TypeEnum,
        Reference: 'Reference' as TypeEnum
    };
}
