export * from './comment.service';
import { CommentService } from './comment.service';
export * from './configs.service';
import { ConfigsService } from './configs.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './nodes.service';
import { NodesService } from './nodes.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './wx.service';
import { WxService } from './wx.service';
export const APIS = [CommentService, ConfigsService, FilesService, LoginService, NodesService, RolesService, TagsService, UsersService, WxService];
