/* 
 * api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Configs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfigsTests
    {
        // TODO uncomment below to declare an instance variable for Configs
        //private Configs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Configs
            //instance = new Configs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Configs
        /// </summary>
        [Test]
        public void ConfigsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Configs
            //Assert.IsInstanceOfType<Configs> (instance, "variable 'instance' is a Configs");
        }


        /// <summary>
        /// Test the property 'AppConfigs'
        /// </summary>
        [Test]
        public void AppConfigsTest()
        {
            // TODO unit test for the property 'AppConfigs'
        }
        /// <summary>
        /// Test the property 'ServiceMessages'
        /// </summary>
        [Test]
        public void ServiceMessagesTest()
        {
            // TODO unit test for the property 'ServiceMessages'
        }
        /// <summary>
        /// Test the property 'PermissionDescriptions'
        /// </summary>
        [Test]
        public void PermissionDescriptionsTest()
        {
            // TODO unit test for the property 'PermissionDescriptions'
        }
        /// <summary>
        /// Test the property 'UiLangs'
        /// </summary>
        [Test]
        public void UiLangsTest()
        {
            // TODO unit test for the property 'UiLangs'
        }

    }

}
