/* 
 * api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NodeDir
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NodeDirTests
    {
        // TODO uncomment below to declare an instance variable for NodeDir
        //private NodeDir instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NodeDir
            //instance = new NodeDir();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NodeDir
        /// </summary>
        [Test]
        public void NodeDirInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NodeDir
            //Assert.IsInstanceOfType<NodeDir> (instance, "variable 'instance' is a NodeDir");
        }


        /// <summary>
        /// Test the property 'Subnodes'
        /// </summary>
        [Test]
        public void SubnodesTest()
        {
            // TODO unit test for the property 'Subnodes'
        }
        /// <summary>
        /// Test the property 'Supnodes'
        /// </summary>
        [Test]
        public void SupnodesTest()
        {
            // TODO unit test for the property 'Supnodes'
        }

    }

}
