/* 
 * api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Query
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QueryTests
    {
        // TODO uncomment below to declare an instance variable for Query
        //private Query instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Query
            //instance = new Query();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Query
        /// </summary>
        [Test]
        public void QueryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Query
            //Assert.IsInstanceOfType<Query> (instance, "variable 'instance' is a Query");
        }


        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Test]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'Where'
        /// </summary>
        [Test]
        public void WhereTest()
        {
            // TODO unit test for the property 'Where'
        }
        /// <summary>
        /// Test the property 'OrderBy'
        /// </summary>
        [Test]
        public void OrderByTest()
        {
            // TODO unit test for the property 'OrderBy'
        }
        /// <summary>
        /// Test the property 'OrderByDesc'
        /// </summary>
        [Test]
        public void OrderByDescTest()
        {
            // TODO unit test for the property 'OrderByDesc'
        }

    }

}
